generatorName: kotlin-spring
inputSpec: ./openapi/openapi.yaml
outputDir: ./backend
additionalProperties:
  modelPackage: larscom.gitlab.ci.dashboard.api.model
  apiPackage: larscom.gitlab.ci.dashboard.api.api
  sourceFolder: src/main/kotlin
  library: spring-cloud
  useSpringBoot3: true
  useTags: true
  interfaceOnly: true
  skipDefaultInterface: true
  enumPropertyNaming: UPPERCASE
  exceptionHandler: false

typeMappings:
  java.time.OffsetDateTime: java.time.Instant
